default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["POSTGRESQL_DATABASE"] || 'bogo_ambiental_api' %>
  pool: <%= ENV["POSTGRESQL_POOL"] || 5 %>
  port: <%= ENV["POSTGRESQL_PORT"] || 5432 %>

development:
  <<: *default
  username: <%= ENV["POSTGRESQL_USER"] || ENV["USER"] || 'postgres' %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>
  database: bogo_ambiental_api_development
  host: <%= ENV["POSTGRESQL_HOST"] || 'localhost' %>

test:
  <<: *default
  database: bogo_ambiental_api_test

production:
  <<: *default
